name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: 19
        java-package: jdk
        distribution: openjdk
        architecture: x64
        check-latest: false

    - name: Build with Maven
      run: mvn clean install
